FROM python:3.12-slim

WORKDIR /app

COPY ../../app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ../../app/ ./

ENV PYTHONUNBUFFERED=1

COPY ../../app/ /app/
COPY deploy/docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

